// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRGiwybvN-7UreNcZmArV7HX8ZPRMcas',
    appId: '1:1040603054231:web:826f57d0aea42a823969d2',
    messagingSenderId: '1040603054231',
    projectId: 'socialappdb-cec6f',
    authDomain: 'socialappdb-cec6f.firebaseapp.com',
    storageBucket: 'socialappdb-cec6f.firebasestorage.app',
    measurementId: 'G-5M0P4BRDC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDr6RWf8e44B0Q6yvCeo_-5-hxoZZuvnM',
    appId: '1:1040603054231:android:c91e17f824747e783969d2',
    messagingSenderId: '1040603054231',
    projectId: 'socialappdb-cec6f',
    storageBucket: 'socialappdb-cec6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEqch-Jw2BpGXCDXxDYQ9WcbZH4S8H9M',
    appId: '1:1040603054231:ios:66ce581cddceba023969d2',
    messagingSenderId: '1040603054231',
    projectId: 'socialappdb-cec6f',
    storageBucket: 'socialappdb-cec6f.firebasestorage.app',
    iosBundleId: 'com.example.socialapp',
  );
}
